# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile for Ubuntu
Vagrant.configure("2") do |config|
  # environment
  ENV['LC_ALL']="en_US.UTF-8"
  config.vm.hostname = "ubuntu-bionic"
  # box
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  # synced folder
  config.vm.synced_folder "../shared", "/mnt/shared"
  # provider
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1536"
  end
  # provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y \
      software-properties-common \
      sudo \
      cron \
      xclip \
      man \
      tree \
      psmisc \
      curl \
      wget \
      rsync \
      vim \
      exuberant-ctags \
      cscope \
      ssh \
      mosh \
      openssh-server \
      git \
      ca-certificates \
      bc \
      jq \
      cpio \
      unzip \
      xz-utils \
      p7zip-full \
      hexedit \
      tmux \
      build-essential \
      gdb \
      gdbserver \
      automake \
      libtool \
      cmake \
      ccache \
      python \
      python3 \
      pkg-config \
      flex \
      bison \
      nasm \
      yasm \
      gawk \
      net-tools \
      iputils-ping \
      netcat \
      socat \
      x11-apps \
      python-dev \
      python3-dev \
      virtualenv \
      unrar \
      gcc-multilib \
      lib32ncurses5-dev \
      lib32z1 \
      valgrind \
      ffmpeg \
      nginx \
      mosquitto \
      mosquitto-clients

  SHELL
end
