# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile for FreeBSD
Vagrant.configure("2") do |config|
  # hostname
  config.vm.hostname = "freebsd-12"
  # ssh
  config.ssh.forward_x11 = true
  # box
  config.vm.box = "generic/freebsd12"
  #config.vm.box = "freebsd/FreeBSD-12.0-STABLE"
  config.vm.box_check_update = false
  # network
  config.vm.network "forwarded_port", guest: 8080, host: 28080
  # synced folder
  # -
  # provider
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1536"
  end
  # provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo pkg update
    sudo pkg install -y \
      git \
      vim \
      wget \
      curl
    cd /usr/local/bin \
      && wget https://raw.githubusercontent.com/aggresss/dotfiles/master/update_dotfiles.sh \
      && chmod +x update_dotfiles.sh
  SHELL
end
