# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile for FreeBSD
Vagrant.configure("2") do |config|
  # box
  config.vm.box = "freebsd/FreeBSD-12.0-STABLE"
  config.vm.box_check_update = false
  # synced folder
  config.vm.synced_folder "../shared", "/mnt/shared"
  # provider
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1536"
  end
  # provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo pkg update
    sudo pkg install -y \
      bash \
      git \
      wget \
      curl \
      vim
  SHELL
end
