# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile for FreeBSD
Vagrant.configure("2") do |config|
  # hostname
  config.vm.hostname = "freebsd-12"
  # ssh
  config.ssh.forward_x11 = true
  # box
  config.vm.box = "generic/freebsd12"
  #config.vm.box = "freebsd/FreeBSD-12.0-STABLE"
  config.vm.box_check_update = false
  # network
  config.vm.network "forwarded_port", guest: 8080, host: 28080
  # synced folder
  # -
  # provider
  ["virtualbox", "hyperv"].each do |provider|
    config.vm.provider provider do |v, override|
      v.memory = "1024"
      # v.cpus = "2"
    end
  end
  # provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo pkg update
    sudo pkg install -y \
      bash \
      git \
      vim \
      wget \
      curl \
      cmake \
      autoconf \
      automake \
      libtool
    wget -P /usr/local/bin https://github.com/aggresss/dotfiles/raw/master/update_dotfiles.sh \
      && chmod 755 /usr/local/bin/update_dotfiles.sh
  SHELL
end
